services:
  database:
    image: mongo:latest
    container_name: mongodb
    networks:
      - backend
    volumes:
      - mongodata:/data/db

  backend:
    build: ./backend/node
    container_name: node
    ports:
      - $BACKENDPORT:3000
    networks:
      - backend
      - frontend
    environment:
      - MONGODB_URI=$MONGODB
    volumes:
      - ./backend/node:/app
      - ./backend/shared:/app/shared
    depends_on:
      - database

  python:
    build: ./backend/python
    container_name: python
    networks:
      - backend
    volumes:
      - ./backend/python:/app
      - ./backend/shared:/app/shared

  frontend:
    build: ./frontend
    container_name: vite
    ports:
      - $FRONTENDPORT:5173
    networks:
      - frontend
    volumes:
      - ./frontend:/app
networks:
  backend:
  frontend:
volumes:
  mongodata:
